name: r_flutter
version: 0.9.0
description: Generate constants for resources which require using them as a String like fonts and assets.

homepage: https://github.com/timfreiheit/r_flutter
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: '^2.0.0'
  path: '>=0.9.0 <2.0.0'
  yaml: ^3.1.0
  recase: '>=4.0.0 < 5.0.0'
  build: '>=2.0.0 <3.0.0'
  build_config: '>=1.0.0 <2.0.0'
  collection: ^1.15.0
  glob: ^2.0.0

dev_dependencies:
  test: any
  build_test: ^2.0.0
  lint: ^1.0.0
