name: r_flutter
version: 0.1.3
author: Tim Freiheit <freiheit.tim@gmail.com>
description: Generate constants for resources which require using them as a String like fonts and assets.

homepage: https://github.com/timfreiheit/R.Flutter
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  path: '>=0.9.0 <2.0.0'
  yaml: ^2.1.15
  recase: ^2.0.1

  build: ^1.1.4
  build_config: ^0.4.0

dev_dependencies:
  test: any
  build_test: any
